@startuml

class Album {
    - nombre: String
    - añoLanzamiento: int
    - disquera: String
    - artistas: String[]
    - canciones: List<Cancion>
    --
    + Album(String nombre, int añoLanzamiento, String disquera, String[] artistas)
    + getNombre(): String
    + getAñoLanzamiento(): int
    + agregarCancion(Cancion cancion): void
    + mostrarAlbum(): void
    + static buscarPorAño(List<Album> albums, int año): void
    + static crearAlbum(String nombre, int añoLanzamiento, String disquera, String[] artistas): Album
}

class Cancion {
    - titulo: String
    - duracion: String
    --
    + Cancion(String titulo, String duracion)
    + getTitulo(): String
    + getDuracion(): String
}

Album "1" o-- "1..n" Cancion : contiene

@enduml